/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IcapRouteImport } from './routes/icap'
import { Route as ApiStudyRouteImport } from './routes/api/study'
import { Route as StudyDeskIndexRouteImport } from './routes/study-desk.index'
import { Route as ApiPublicIcapRouteImport } from './routes/api/public/icap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IcapRoute = IcapRouteImport.update({
  id: '/icap',
  path: '/icap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyRoute = ApiStudyRouteImport.update({
  id: '/api/study',
  path: '/api/study',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyDeskIndexRoute = StudyDeskIndexRouteImport.update({
  id: '/study-desk/',
  path: '/study-desk/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIcapRoute = ApiPublicIcapRouteImport.update({
  id: '/api/public/icap',
  path: '/api/public/icap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/icap': typeof IcapRoute
  '/api/study': typeof ApiStudyRoute
  '/study-desk/': typeof StudyDeskIndexRoute
  '/api/public/icap': typeof ApiPublicIcapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/icap': typeof IcapRoute
  '/api/study': typeof ApiStudyRoute
  '/study-desk': typeof StudyDeskIndexRoute
  '/api/public/icap': typeof ApiPublicIcapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/icap': typeof IcapRoute
  '/api/study': typeof ApiStudyRoute
  '/study-desk/': typeof StudyDeskIndexRoute
  '/api/public/icap': typeof ApiPublicIcapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/icap' | '/api/study' | '/study-desk/' | '/api/public/icap'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/auth' | '/icap' | '/api/study' | '/study-desk' | '/api/public/icap'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/icap'
    | '/api/study'
    | '/study-desk/'
    | '/api/public/icap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  IcapRoute: typeof IcapRoute
  ApiStudyRoute: typeof ApiStudyRoute
  StudyDeskIndexRoute: typeof StudyDeskIndexRoute
  ApiPublicIcapRoute: typeof ApiPublicIcapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icap': {
      id: '/icap'
      path: '/icap'
      fullPath: '/icap'
      preLoaderRoute: typeof IcapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study': {
      id: '/api/study'
      path: '/api/study'
      fullPath: '/api/study'
      preLoaderRoute: typeof ApiStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-desk/': {
      id: '/study-desk/'
      path: '/study-desk'
      fullPath: '/study-desk/'
      preLoaderRoute: typeof StudyDeskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/icap': {
      id: '/api/public/icap'
      path: '/api/public/icap'
      fullPath: '/api/public/icap'
      preLoaderRoute: typeof ApiPublicIcapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  IcapRoute: IcapRoute,
  ApiStudyRoute: ApiStudyRoute,
  StudyDeskIndexRoute: StudyDeskIndexRoute,
  ApiPublicIcapRoute: ApiPublicIcapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
